"""Narrow Aurora Trust provider boundaries and deterministic test doubles."""

from __future__ import annotations

from typing import Any, Protocol

from .security_models import ClockTrustState, CredentialID, SecurityNodeID, TrustDomainID
from .security_secrets import SecretBytes


class SecureRandomProvider(Protocol):
    def bytes(self, count: int) -> SecretBytes: ...


class SigningKeyHandle(Protocol):
    @property
    def key_id(self) -> str: ...
    def sign_digest(self, digest: bytes) -> bytes: ...


class CryptoProvider(Protocol):
    def sha256(self, value: bytes) -> bytes: ...
    def hmac_sha256(self, key: SecretBytes, value: bytes) -> bytes: ...


class Spake2PlusOperation(Protocol):
    def receive_peer_share(self, encoded_share: bytes) -> bytes: ...
    def verify_confirmation(self, confirmation: bytes) -> bool: ...


class AeadProvider(Protocol):
    def seal(self, key: SecretBytes, plaintext: SecretBytes, nonce: bytes, associated_data: bytes) -> bytes: ...
    def open(self, key: SecretBytes, ciphertext: bytes, nonce: bytes, associated_data: bytes) -> SecretBytes: ...


class IdentityKeyProvider(Protocol):
    def generate(self) -> SigningKeyHandle: ...


class CredentialValidator(Protocol):
    def validate(self, credential: bytes, expected_domain: TrustDomainID, expected_node: SecurityNodeID) -> Any: ...


class SecurityClock(Protocol):
    def monotonic_ns(self) -> int: ...
    def utc_timestamp(self) -> str | None: ...
    @property
    def trust_state(self) -> ClockTrustState: ...


class SecureTimeCheckpoint(Protocol):
    def load(self) -> tuple[str, int] | None: ...
    def store(self, timestamp: str, monotonic_ns: int) -> None: ...


class IdentityStore(Protocol):
    def stage(self, credential_id: CredentialID, credential: bytes, key: SigningKeyHandle) -> None: ...
    def commit(self, credential_id: CredentialID) -> None: ...
    def rollback(self) -> None: ...


class TrustDomainAuthority(Protocol):
    def issue(self, request: Any) -> bytes: ...


class EnrollmentPolicy(Protocol):
    def approve(self, request: Any) -> bool: ...


class AuthorizationPolicy(Protocol):
    def permissions(self, principal: Any) -> frozenset[str]: ...


class AuditSink(Protocol):
    def record(self, event: str, public_fields: dict[str, Any]) -> None: ...


class RevocationStore(Protocol):
    def contains(self, credential_id: CredentialID) -> bool: ...
    @property
    def epoch(self) -> int: ...
