#!/usr/bin/env python3
"""Generate schema/registry.json from the compact catalog below. Run from repo root."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ALL = ["conductor", "prism", "lyric", "bridge", "tool", "simulator", "remote"]
AUTH = ["conductor", "prism", "simulator"]
REMOTE_CLIENT = ["remote", "tool", "simulator"]

# type, min_protocol, profiles, capability, direction, senders, dests, qos, qos_allowed,
# ack, idempotent, response, legal_before_hs, security, schema
ROWS = [
    ("session.hello", "1.0", ["core"], None, "request",
     ALL, ["node"],
     "reliable", ["reliable"], "required", False, "session.hello_ack", True, "handshake",
     "session/messages.schema.json#/$defs/hello"),
    ("session.hello_ack", "1.0", ["core"], None, "response",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, True, "handshake",
     "session/messages.schema.json#/$defs/hello_ack"),
    ("session.goodbye", "1.0", ["core"], None, "event",
     ALL, ["node"],
     "best_effort", ["best_effort", "reliable"], "none", False, None, False, "handshake",
     "session/messages.schema.json#/$defs/goodbye"),
    ("discovery.query", "1.0", ["core"], None, "advertisement",
     ["conductor", "tool", "simulator", "remote"], ["broadcast"],
     "best_effort", ["best_effort"], "none", False, None, True, "discovery",
     "discovery/messages.schema.json#/$defs/query"),
    ("discovery.advertisement", "1.0", ["core"], None, "advertisement",
     ALL, ["broadcast"],
     "best_effort", ["best_effort"], "none", False, None, True, "discovery",
     "discovery/messages.schema.json#/$defs/advertisement"),
    ("command.execute", "1.0", ["core"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "component"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "command/messages.schema.json#/$defs/execute"),
    ("command.ack", "1.0", ["core"], None, "response",
     ["conductor", "prism", "lyric", "bridge", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "control",
     "command/messages.schema.json#/$defs/ack"),
    ("state.request", "1.0", ["core"], None, "request",
     ALL, ["node"],
     "reliable", ["reliable"], "optional", False, "state.snapshot", False, "state",
     "state/messages.schema.json#/$defs/request"),
    ("state.snapshot", "1.0", ["core"], None, "response",
     ["conductor", "prism", "lyric", "bridge", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "state/messages.schema.json#/$defs/snapshot"),
    ("state.delta", "1.0", ["core"], None, "event",
     ["conductor", "prism", "lyric", "bridge"], ["node", "session"],
     "latest", ["latest", "reliable"], "none", False, None, False, "state",
     "state/messages.schema.json#/$defs/delta"),
    ("health.heartbeat", "1.0", ["core"], "health.heartbeat", "event",
     ALL, ["session"],
     "latest", ["latest"], "none", False, None, False, "health",
     "health/messages.schema.json#/$defs/heartbeat"),
    ("health.warning", "1.0", ["core"], "health.heartbeat", "event",
     ["conductor", "prism", "lyric", "bridge"], ["session"],
     "reliable", ["reliable"], "none", False, None, False, "health",
     "health/messages.schema.json#/$defs/warning"),
    ("health.snapshot", "1.0", ["core"], "health.heartbeat", "response",
     ["conductor", "prism", "lyric", "bridge"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "health",
     "health/messages.schema.json#/$defs/snapshot"),
    ("capability.list", "1.0", ["core"], None, "response",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "handshake",
     "capability/messages.schema.json#/$defs/list"),
    ("capability.changed", "1.0", ["core"], None, "event",
     ["conductor", "prism", "lyric", "bridge"], ["session"],
     "reliable", ["reliable"], "none", False, None, False, "handshake",
     "capability/messages.schema.json#/$defs/changed"),
    ("error.report", "1.0", ["core"], None, "event",
     ALL, ["node", "session"],
     "reliable", ["reliable"], "none", False, None, True, "control",
     "error/messages.schema.json#/$defs/report"),
    ("config.schema", "1.0", ["bridge"], "bridge.config", "response",
     ["bridge"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "config",
     "config/schema.schema.json"),
    ("config.get", "1.0", ["bridge"], "bridge.config", "request",
     ["conductor", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "required", False, "config.result", False, "config",
     "config/get.schema.json"),
    ("config.set", "1.0", ["bridge"], "bridge.config", "request",
     ["conductor", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "required", True, "config.result", False, "config",
     "config/set.schema.json"),
    ("config.result", "1.0", ["bridge"], "bridge.config", "response",
     ["bridge"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "config",
     "config/result.schema.json"),
    ("log.event", "1.0", ["core"], None, "event",
     ["conductor", "prism", "lyric", "bridge"], ["session"],
     "best_effort", ["best_effort"], "none", False, None, False, "telemetry",
     "log/messages.schema.json#/$defs/event"),
    ("telemetry.metric", "1.0", ["core"], None, "event",
     ["conductor", "prism", "lyric", "bridge"], ["session"],
     "latest", ["latest", "best_effort"], "none", False, None, False, "telemetry",
     "telemetry/messages.schema.json#/$defs/metric"),
    ("telemetry.batch", "1.0", ["core"], None, "event",
     ["conductor", "prism", "lyric", "bridge"], ["session"],
     "best_effort", ["best_effort"], "none", False, None, False, "telemetry",
     "telemetry/messages.schema.json#/$defs/batch"),
    ("show.load", "1.0", ["conductor", "prism"], None, "request",
     ["conductor", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "show/messages.schema.json#/$defs/load"),
    ("show.ready", "1.0", ["prism", "lyric", "bridge"], None, "event",
     ["prism", "lyric", "bridge"], ["session"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "show/messages.schema.json#/$defs/ready"),
    ("show.position", "1.0", ["conductor"], None, "event",
     ["conductor"], ["session"],
     "latest", ["latest"], "none", False, None, False, "state",
     "show/messages.schema.json#/$defs/position"),
    ("show.prepare", "1.2", ["conductor"], "asset.conformance", "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "show.conformance", False, "control",
     "show/messages.schema.json#/$defs/prepare"),
    ("show.conformance", "1.2", ["conductor", "prism", "lyric", "bridge"], "asset.conformance", "response",
     ["prism", "lyric", "bridge"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "show/messages.schema.json#/$defs/conformance"),
    ("show.verify", "1.2", ["conductor"], "asset.conformance", "request",
     ["conductor", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "required", False, "command.ack", False, "control",
     "show/messages.schema.json#/$defs/verify"),
    ("show.arm", "1.2", ["conductor"], "asset.conformance", "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "show.armed", False, "control",
     "show/messages.schema.json#/$defs/arm"),
    ("show.armed", "1.2", ["conductor", "prism", "lyric", "bridge"], "asset.conformance", "response",
     ["conductor", "prism", "lyric", "bridge"], ["session"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "show/messages.schema.json#/$defs/armed"),
    ("show.disarm", "1.2", ["conductor"], "asset.conformance", "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", False, "command.ack", False, "control",
     "show/messages.schema.json#/$defs/disarm"),
    ("song.select", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "song/messages.schema.json#/$defs/select"),
    ("song.start", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "song/messages.schema.json#/$defs/start"),
    ("song.stop", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "song/messages.schema.json#/$defs/stop"),
    ("song.position", "1.0", ["conductor"], None, "event",
     ["conductor"], ["session"],
     "latest", ["latest"], "none", False, None, False, "state",
     "song/messages.schema.json#/$defs/position"),
    ("section.enter", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "section/messages.schema.json#/$defs/enter"),
    ("section.exit", "1.0", ["conductor"], None, "event",
     ["conductor"], ["session"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "section/messages.schema.json#/$defs/exit"),
    ("section.position", "1.0", ["conductor"], None, "event",
     ["conductor"], ["session"],
     "latest", ["latest"], "none", False, None, False, "state",
     "section/messages.schema.json#/$defs/position"),
    ("cue.go", "1.0", ["prism"], "prism.cue_control", "request",
     ["conductor", "tool", "simulator"], ["node", "component"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "cue/messages.schema.json#/$defs/go"),
    ("cue.fire", "1.0", ["prism"], "prism.cue_control", "request",
     ["conductor", "tool", "simulator"], ["node", "component"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "cue/messages.schema.json#/$defs/fire"),
    ("cue.stop", "1.0", ["prism"], "prism.cue_control", "request",
     ["conductor", "tool", "simulator"], ["node", "component"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "cue/messages.schema.json#/$defs/stop"),
    ("transport.play", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "transport/messages.schema.json#/$defs/play"),
    ("transport.pause", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "transport/messages.schema.json#/$defs/pause"),
    ("transport.stop", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "transport/messages.schema.json#/$defs/stop"),
    ("transport.seek", "1.0", ["conductor"], None, "request",
     ["conductor", "tool", "simulator"], ["node", "session"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "transport/messages.schema.json#/$defs/seek"),
    ("bridge.status", "1.0", ["bridge"], "bridge.status", "event",
     ["bridge"], ["session"],
     "latest", ["latest", "reliable"], "none", False, None, False, "state",
     "bridge/messages.schema.json#/$defs/status"),
    ("bridge.blackout", "1.0", ["bridge"], "bridge.blackout", "request",
     ["conductor", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "bridge/messages.schema.json#/$defs/blackout"),
    ("manifest.get", "1.2", ["conductor"], "asset.conformance", "request",
     ALL, ["node"],
     "reliable", ["reliable"], "required", False, "manifest.report", False, "state",
     "asset/messages.schema.json#/$defs/manifest_get"),
    ("manifest.report", "1.2", ["conductor"], "asset.conformance", "response",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "asset/messages.schema.json#/$defs/manifest_report"),
    ("asset.inventory", "1.2", ["prism", "lyric", "bridge"], "asset.conformance", "event",
     ["prism", "lyric", "bridge"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "asset/messages.schema.json#/$defs/inventory"),
    ("asset.status", "1.2", ["prism", "lyric", "bridge"], "asset.conformance", "event",
     ["prism", "lyric", "bridge"], ["node"],
     "latest", ["latest", "reliable"], "none", False, None, False, "state",
     "asset/messages.schema.json#/$defs/status"),
    ("asset.required", "1.2", ["conductor"], "asset.conformance", "event",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "asset/messages.schema.json#/$defs/required"),
    ("asset.sync", "1.2", ["conductor"], "asset.conformance", "request",
     ["conductor", "tool", "simulator"], ["node"],
     "reliable", ["reliable"], "required", False, "asset.sync_result", False, "transfer",
     "asset/messages.schema.json#/$defs/sync"),
    ("asset.sync_result", "1.2", ["prism", "lyric", "bridge"], "asset.conformance", "response",
     ["prism", "lyric", "bridge"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "transfer",
     "asset/messages.schema.json#/$defs/sync_result"),
    ("resource.offer", "1.2", ["core"], "resource.transfer", "request",
     ALL, ["node"],
     "reliable", ["reliable"], "required", False, "resource.accept", False, "transfer",
     "resource/messages.schema.json#/$defs/offer"),
    ("resource.accept", "1.2", ["core"], "resource.transfer", "response",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "transfer",
     "resource/messages.schema.json#/$defs/accept"),
    ("resource.reject", "1.2", ["core"], "resource.transfer", "response",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "transfer",
     "resource/messages.schema.json#/$defs/reject"),
    ("resource.chunk", "1.2", ["core"], "resource.transfer", "event",
     ALL, ["node"],
     "reliable", ["reliable"], "none", True, None, False, "transfer",
     "resource/messages.schema.json#/$defs/chunk"),
    ("resource.complete", "1.2", ["core"], "resource.transfer", "event",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, "resource.transfer_result", False, "transfer",
     "resource/messages.schema.json#/$defs/complete"),
    ("resource.transfer_result", "1.2", ["core"], "resource.transfer", "response",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "transfer",
     "resource/messages.schema.json#/$defs/transfer_result"),
    ("resource.activate", "1.2", ["core"], "resource.transfer", "request",
     ALL, ["node"],
     "reliable", ["reliable"], "required", True, "resource.activation_result", False, "transfer",
     "resource/messages.schema.json#/$defs/activate"),
    ("resource.activation_result", "1.2", ["core"], "resource.transfer", "response",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "transfer",
     "resource/messages.schema.json#/$defs/activation_result"),
    ("resource.cancel", "1.2", ["core"], "resource.transfer", "request",
     ALL, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "transfer",
     "resource/messages.schema.json#/$defs/cancel"),
    ("participant.identity", "1.2", ["lyric", "conductor"], "lyric.assignment", "event",
     ["conductor", "lyric"], ["node", "session"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "participant/messages.schema.json#/$defs/identity"),
    ("participant.preference", "1.2", ["lyric", "conductor"], "lyric.assignment", "event",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "participant/messages.schema.json#/$defs/preference"),
    ("participant.assignment", "1.2", ["lyric", "conductor"], "lyric.assignment", "request",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "participant/messages.schema.json#/$defs/assignment"),
    ("chart.catalog", "1.2", ["lyric", "conductor"], "lyric.assignment", "event",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "chart/messages.schema.json#/$defs/catalog"),
    ("chart.metadata", "1.2", ["lyric", "conductor"], "lyric.assignment", "event",
     ["conductor", "lyric"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "chart/messages.schema.json#/$defs/metadata"),
    ("chart.assignment", "1.2", ["lyric", "conductor"], "lyric.assignment", "request",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "chart/messages.schema.json#/$defs/assignment"),
    ("chart.assignment_set", "1.2", ["lyric", "conductor"], "lyric.assignment", "request",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "chart/messages.schema.json#/$defs/assignment_set"),
    ("lyric.assignment_manifest", "1.2", ["lyric", "conductor"], "lyric.assignment", "event",
     ["conductor"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "lyric/messages.schema.json#/$defs/assignment_manifest"),
    ("lyric.assignment_status", "1.2", ["lyric"], "lyric.assignment", "event",
     ["lyric"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "lyric/messages.schema.json#/$defs/assignment_status"),
    ("lyric.client_ready", "1.2", ["lyric"], "lyric.assignment", "event",
     ["lyric"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "lyric/messages.schema.json#/$defs/client_ready"),
    ("lyric.ready", "1.2", ["lyric"], "lyric.assignment", "event",
     ["lyric"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "lyric/messages.schema.json#/$defs/ready"),
    ("remote.hello", "1.2", ["remote"], "remote.profile", "request",
     REMOTE_CLIENT, ["node"],
     "reliable", ["reliable"], "required", False, "remote.hello_ack", False, "handshake",
     "remote/messages.schema.json#/$defs/hello"),
    ("remote.hello_ack", "1.2", ["remote"], "remote.profile", "response",
     AUTH, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "handshake",
     "remote/messages.schema.json#/$defs/hello_ack"),
    ("remote.layout.request", "1.2", ["remote"], "remote.layout", "request",
     REMOTE_CLIENT, ["node"],
     "reliable", ["reliable"], "optional", False, "remote.layout.report", False, "state",
     "remote/messages.schema.json#/$defs/layout_request"),
    ("remote.layout.report", "1.2", ["remote"], "remote.layout", "response",
     AUTH, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "remote/messages.schema.json#/$defs/layout_report"),
    ("remote.control.invoke", "1.2", ["remote"], "remote.control.invoke", "request",
     REMOTE_CLIENT, ["node"],
     "reliable", ["reliable", "latest"], "required", True, "command.ack", False, "control",
     "remote/remote_control_invocation.schema.json"),
    ("remote.control.state", "1.2", ["remote"], "remote.control.state", "event",
     AUTH, ["node", "session"],
     "latest", ["latest", "reliable"], "none", False, None, False, "state",
     "remote/remote_control_state.schema.json"),
    ("remote.control.snapshot", "1.2", ["remote"], "remote.control.state", "response",
     AUTH, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "remote/messages.schema.json#/$defs/control_snapshot"),
    ("remote.permissions", "1.2", ["remote"], "remote.profile", "response",
     AUTH, ["node"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "remote/remote_permission_set.schema.json"),
    ("remote.permissions.changed", "1.2", ["remote"], "remote.profile", "event",
     AUTH, ["node", "session"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "remote/remote_permission_set.schema.json"),
    ("remote.readiness", "1.2", ["remote"], "remote.readiness", "request",
     REMOTE_CLIENT, ["node"],
     "reliable", ["reliable"], "optional", False, "remote.readiness.changed", False, "state",
     "remote/remote_readiness.schema.json"),
    ("remote.readiness.changed", "1.2", ["remote"], "remote.readiness", "event",
     AUTH, ["session"],
     "reliable", ["reliable"], "none", False, None, False, "state",
     "remote/remote_readiness.schema.json"),
    ("remote.navigation.request", "1.2", ["remote"], "remote.navigation.song", "request",
     REMOTE_CLIENT, ["node"],
     "reliable", ["reliable"], "required", True, "command.ack", False, "control",
     "remote/messages.schema.json#/$defs/navigation_request"),
    ("remote.navigation.state", "1.2", ["remote"], "remote.navigation.song", "event",
     ["conductor", "simulator"], ["session"],
     "latest", ["latest", "reliable"], "none", False, None, False, "state",
     "remote/messages.schema.json#/$defs/navigation_state"),
    ("remote.presentation.state", "1.2", ["remote"], "remote.presentation", "event",
     AUTH, ["session"],
     "latest", ["latest", "best_effort"], "none", False, None, False, "telemetry",
     "remote/remote_presentation.schema.json"),
    ("remote.momentary.refresh", "1.2", ["remote"], "remote.control.momentary", "request",
     REMOTE_CLIENT, ["node"],
     "reliable", ["reliable"], "optional", True, "command.ack", False, "control",
     "remote/messages.schema.json#/$defs/momentary_refresh"),
    ("remote.error", "1.2", ["remote"], "remote.profile", "event",
     AUTH + ["remote", "tool"], ["node"],
     "reliable", ["reliable"], "none", False, None, False, "control",
     "remote/messages.schema.json#/$defs/error"),
]


def main() -> None:
    entries = []
    for row in ROWS:
        (typ, minp, profiles, cap, direction, senders, dests, qos, qos_ok,
         ack, idem, resp, before, security, schema) = row
        entries.append({
            "type": typ,
            "min_protocol": minp,
            "max_protocol": None,
            "profiles": profiles,
            "required_capability": cap,
            "min_capability_version": "1.0" if cap else None,
            "direction": direction,
            "valid_senders": senders,
            "valid_destinations": dests,
            "qos_default": qos,
            "qos_allowed": qos_ok,
            "ack": ack,
            "idempotent": idem,
            "idempotency_key": "payload.idempotency_key" if idem else None,
            "response_type": resp,
            "correlation": "copy_or_message_id",
            "causation": "set_on_derived_state",
            "legal_before_handshake": before,
            "security_class": security,
            "schema": schema,
        })
    out = ROOT / "schema" / "registry.json"
    payload = json.dumps({"version": "1.2", "messages": entries}, indent=2) + "\n"
    out.write_text(payload)
    packaged = ROOT / "python" / "src" / "acp" / "data" / "registry.json"
    packaged.parent.mkdir(parents=True, exist_ok=True)
    packaged.write_text(payload)
    swift = ROOT / "Sources" / "AuroraACP" / "Session" / "registry.json"
    swift.parent.mkdir(parents=True, exist_ok=True)
    swift.write_text(payload)
    print(f"wrote {out} ({len(entries)} messages)")


if __name__ == "__main__":
    main()
